image:
  name: stm32cubeide_cppcheck:latest

stages:
  - cppcheck
  - build
  - test


variables:
  GIT_SUBMODULE_STRATEGY: recursive

  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/ci-test/${CI_COMMIT_TAG}"


cppcheck:
  stage: cppcheck
  script: 
    - cppcheck --enable=warning --error-exitcode=1 --suppress=missingIncludeSystem --verbose -U EXTENDED_DEBUG -U HSE_VALUE -U HSI_VALUE -U LSE_VALUE -U LSI_VALUE ${CI_PROJECT_DIR}/Core/ -I ${CI_PROJECT_DIR}/Core/Inc

build:
  stage: build
  script:
    - /opt/st/stm32cubeide_1.12.1/stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -cleanBuild all -import ${CI_PROJECT_DIR}/ -no-indexer
  artifacts:
    name: "Firmware_${CI_PROJECT_NAME}_${CI_JOB_STARTED_AT}"
    paths:
      - Debug/*.elf
      - Release/*.elf
      - Extended_debug/*.elf

test:
  stage: test
  script: 
    - echo "Nothing tested really... tests will be added soon"
